# Generated by Django 4.0 on 2022-02-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('Car_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Brand', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('Car_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=15)),
                ('Model', models.IntegerField()),
                ('Type', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback')], max_length=20)),
                ('Top_Speed', models.IntegerField()),
                ('Tank_Size', models.IntegerField()),
            ],
        ),
    ]
