# Generated by Django 4.0.3 on 2022-03-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('Name', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('BrandImage', models.ImageField(upload_to='frontend\\static\\media')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Front', models.ImageField(upload_to='frontend\\static\\media')),
                ('Back', models.ImageField(upload_to='frontend\\static\\media')),
                ('Side', models.ImageField(upload_to='frontend\\static\\media')),
                ('Interior_Front', models.ImageField(upload_to='frontend\\static\\media')),
                ('Interior_Back', models.ImageField(upload_to='frontend\\static\\media')),
                ('On_Road', models.ImageField(upload_to='frontend\\static\\media')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Type', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Sport', 'Sport')], max_length=20)),
                ('Top_Speed', models.IntegerField()),
                ('Tank_Size', models.IntegerField()),
                ('Release_Date', models.DateField()),
                ('Brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.brand')),
                ('Images', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.image')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('Car_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Model', models.IntegerField(default=2005)),
                ('Brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.brand')),
            ],
        ),
    ]
