# Generated by Django 4.0.3 on 2022-03-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='Type',
        ),
        migrations.AddField(
            model_name='model',
            name='Year',
            field=models.IntegerField(choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], default=2015),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='Model',
            field=models.IntegerField(default=(2005, '20')),
        ),
        migrations.AlterField(
            model_name='model',
            name='Name',
            field=models.CharField(max_length=25),
        ),
    ]
