# Generated by Django 4.0 on 2022-02-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.AddField(
            model_name='car',
            name='Brand',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
