# Generated by Django 4.0.3 on 2022-03-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_model_type_model_year_alter_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='Electric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='model',
            name='Type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Sport', 'Sport')], default='Sedan', max_length=20),
        ),
        migrations.AlterField(
            model_name='model',
            name='Tank_Size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
