# Generated by Django 4.0.3 on 2022-03-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_model_electric_model_type_alter_model_tank_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='Release_Date',
        ),
    ]
