# Generated by Django 4.0 on 2022-02-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_brand_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Model',
            field=models.IntegerField(default=2005),
        ),
    ]
