# Generated by Django 4.0.3 on 2022-03-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Added',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
