# Generated by Django 4.0.3 on 2022-03-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_model_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='Milage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='Top_Speed',
            field=models.IntegerField(null=True),
        ),
    ]
