# Generated by Django 4.0.3 on 2022-03-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_car_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
