# Generated by Django 4.0.3 on 2022-03-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_model_milage_alter_model_top_speed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
