# Generated by Django 4.0.3 on 2022-03-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_car_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Added',
        ),
    ]
