# Generated by Django 4.0.3 on 2022-03-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='Electric',
        ),
        migrations.AddField(
            model_name='model',
            name='Power',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Hydrogen', 'Hydrogen')], default='Gas', max_length=12),
        ),
        migrations.AlterField(
            model_name='model',
            name='Milage',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='Price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='Tank_Size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='Top_Speed',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
