# Generated by Django 4.0.3 on 2022-03-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_car_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Details',
        ),
    ]
