# Generated by Django 4.0.3 on 2022-04-13 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_model_electric_model_power_alter_model_milage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Created_at', models.DateField(auto_now_add=True)),
                ('Body', models.FilePathField(match='\\.md$', path='Cars\\blogs', recursive=True)),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.model')),
            ],
        ),
    ]
