# Generated by Django 4.0.3 on 2022-04-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Body',
            field=models.FilePathField(path='Cars/blogs', recursive=True),
        ),
    ]
