# Generated by Django 4.0.3 on 2022-04-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.model'),
        ),
    ]
