# Generated by Django 4.0.3 on 2022-04-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_blog_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Thumbnail',
            field=models.ImageField(null=True, upload_to='frontend\\static\\media\\Thumbnails'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='BrandImage',
            field=models.ImageField(null=True, upload_to='frontend\\static\\media\\Brands'),
        ),
        migrations.AlterField(
            model_name='image',
            name='Back',
            field=models.ImageField(null=True, upload_to='frontend\\static\\media\\Backview'),
        ),
        migrations.AlterField(
            model_name='image',
            name='Front',
            field=models.ImageField(null=True, upload_to='frontend\\static\\media\\Frontview'),
        ),
        migrations.AlterField(
            model_name='image',
            name='Interior_Back',
            field=models.ImageField(null=True, upload_to='frontend\\static\\media\\InteriorBack'),
        ),
        migrations.AlterField(
            model_name='image',
            name='Interior_Front',
            field=models.ImageField(null=True, upload_to='frontend\\static\\media\\InteriorFront'),
        ),
        migrations.AlterField(
            model_name='image',
            name='On_Road',
            field=models.ImageField(null=True, upload_to='frontend\\static\\media\\Onroad'),
        ),
        migrations.AlterField(
            model_name='image',
            name='Side',
            field=models.ImageField(null=True, upload_to='frontend\\static\\media\\Sideview'),
        ),
    ]
